### ISSUE TITLE
誤植 5.3項

### ISSUE THREAD

**Issue by Toshahiko** [argama147/lets_make_library#2]
libinterface.hのextern "C"の中の関数名が間違っています。
createはcreateInstance、destroyはdeleteInstanceだと思います。

**Comment by argama147** [comment]
Toshahiko 様
ご指摘ありがとうございます。
ご指摘の通り、5.3項の関数名が間違っておりました。
サンプルコードに合わせ、createInstance、deleteInstanceを関数名とするのが正しいです。
正誤表に記載させていただきます。
ご連絡いただき、ありがとうございました。
