### ISSUE TITLE
「2.3.2 Ubuntuの動的リンク」でビルドできなかったので、オプション-ldlを追加

### ISSUE THREAD

**Issue by tsutsuji86** [argama147/lets_make_library#3]
はじめまして、tsutsuji86と申します。

「2.3.2 Ubuntuの動的リンク」を、Windows 10上のWSL（Ubuntu）で試したところ、
動的リンクでライブラリをロードする側をビルドするときに、
以下のエラーが発生しました。

/usr/bin/ld: /tmp/ccEmZo7J.o: in function `main':
main.c:(.text+0x19): undefined reference to `dlopen'
/usr/bin/ld: main.c:(.text+0x37): undefined reference to `dlsym'
/usr/bin/ld: main.c:(.text+0x61): undefined reference to `dlerror'
/usr/bin/ld: main.c:(.text+0x8b): undefined reference to `dlclose'
/usr/bin/ld: main.c:(.text+0x92): undefined reference to `dlerror'

ググってみると、どうやらlibdlを追加しないといけないようなので、
ビルドオプションに-ldlを追加したところ、ビルドすることができました。

また、ビルドした実行ファイルを動作させるためには、
main.cの13行目を
    void *handle = dlopen(LIB_NAME(hello), RTLD_LAZY);
から
    void *handle = dlopen(LIB_NAME(libhello), RTLD_LAZY);
に修正する必要がありました。

**Comment by argama147** [comment]
tsutsuji86様

坂本です。
本書をお読みいただき、また、コメントをいただきありがとうございます。

まず整理させていただきたいのですが、Ubuntuの「動的リンク」、「動的ロード」、どちらの話でしょうか。情報が混ざっているような気がします。
dlopenを使用する場合は動的ロードの話になります。

Ubuntuの動的リンクであれば、
・記述されている場所：2.3.2 Ubuntuの動的リンク
・サンプルコード：C_Command/StaticLinkDynamicLink
Ubuntuの動的ロードであれば、
・記述されている場所：2.4.2 Ubuntuの動的ロード
・サンプルコード：C_Command/DynamicLoad1
になります。
-ldlが必要なのは動的ロードの場合です。P.29 の【2】において、「-ldl」について説明があります。

本書執筆時点でWSL上での動作確認は行っていなかった為、私のPC（Windows10）にWSL/Ubuntuをインストールして試してみたところ、特に問題なく動作しています。

・Ubuntuの動的リンク

動作ログ
```
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink$ pwd
/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink$ cd makeLibrary/
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/makeLibrary$ gcc -shared -fPIC -o libhello.so -I./include ./src/word.c
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/makeLibrary$ ls
include  libhello.so  src  word.o
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/makeLibrary$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/makeLibrary$ cd ../useLibrary/
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/useLibrary$ gcc main.c -I../makeLibrary/include -L../makeLibrary -o HelloWorld -lhello
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/useLibrary$ ls
HelloWorld  main.c
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/StaticLinkDynamicLink/useLibrary$ ./HelloWorld
Hello, World!
```

・Ubuntuの動的ロード

※準備
C_Command/DynamicLoad1/useLibrary/main.hで
「#define LIB_EXT ".dll"    // For Windows」をコメントアウトし、
「#define LIB_EXT ".so"     // For Linux」
を有効にした状態にしておく。

動作ログ

```
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1$ pwd
/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/makeLibrary$ gcc -shared -fPIC -I./include -o hello.so ./src/word.c
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/makeLibrary$ ls
hello.so  include  src
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/makeLibrary$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/makeLibrary$ cd ../useLibrary/
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/useLibrary$ gcc main.c -o HelloWorld -I../makeLibrary/include -ldl
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/useLibrary$ ls
HelloWorld  main.c  main.h
argama147@DESKTOP-DN47PJF:/mnt/c/book/git/lets_make_library/C_Command/DynamicLoad1/useLibrary$ ./HelloWorld
Hello, World!

```

もし、まだ疑問が残るようでしたら気軽にご相談ください。その際は上記のように動作ログを合わせて情報をいただけるとうれしいです。

以上、よろしくお願い致します。

**Comment by tsutsuji86** [comment]
坂本様

tsutsuji86です。
ご返信ありがとうございます。

申し訳ございません。
ご指摘の通り、対象サンプルを混同しておりました。

Ubuntuの動的リンクを試すのに、
・記述されている場所：2.3.2 Ubuntuの動的リンク
の内容を、
・サンプルコード：C_Command/DynamicLoad1
で試していました。

静的リンクと動的リンクのサンプルが共通の
C_Command/StaticLinkDynamicLink
であることを見落としておりました。

お手数をお掛けしました。
重ね重ね申し訳ございませんでした。

**Comment by tsutsuji86** [comment]
「2.3.2 Ubuntuの動的リンク」に関して、
・サンプルコード：C_Command/StaticLinkDynamicLink
が本書の通り、ビルドおよび実行できることを確認しました。

ちなみに、「2.3.1 Cygwinの動的リンク」の
「実行結果：Cygwinの動的リンク」の最初のディレクトリ移動の記述箇所をみると、
$cd /cygdrive/C/make_library/C_Command/DynamicLoad1/makeLibrary/
となっているようです。
正しくは、
$cd /cygdrive/C/make_library/C_Command/StaticLinkDynamicLink/makeLibrary/
でしょうか。
ご確認のほど、よろしくお願いいたします。

私が読んでいるのは、Kindle版です。
既に対応済みでしたら、ご容赦ください。

**Comment by argama147** [comment]
> 坂本様
> 
> tsutsuji86です。 ご返信ありがとうございます。
> 
> 申し訳ございません。 ご指摘の通り、対象サンプルを混同しておりました。
> 
> Ubuntuの動的リンクを試すのに、 ・記述されている場所：2.3.2 Ubuntuの動的リンク の内容を、 ・サンプルコード：C_Command/DynamicLoad1 で試していました。
> 
> 静的リンクと動的リンクのサンプルが共通の C_Command/StaticLinkDynamicLink であることを見落としておりました。
> 
> お手数をお掛けしました。 重ね重ね申し訳ございませんでした。

**Comment by argama147** [comment]
動作が確認できたようでよかったです。
>ちなみに、「2.3.1 Cygwinの動的リンク」の
>「実行結果：Cygwinの動的リンク」の最初のディレクトリ移動の記述箇所をみると、
>$cd /cygdrive/C/make_library/C_Command/DynamicLoad1/makeLibrary/
>となっているようです。
については誤記ですね。ご指摘ありがとうございます。
